### ISSUE TITLE
Pysnip doesn't compiling with latest cython (0.22)

### ISSUE THREAD

**Issue by noway421** [NateShoffner/PySnip#1]
Here is stdout of `build_all.sh`:
```
Compiling ./pyspades/vxl.pyx because it changed.
Compiling ./pyspades/bytes.pyx because it changed.
Compiling ./pyspades/packet.pyx because it changed.
Compiling ./pyspades/contained.pyx because it changed.
Compiling ./pyspades/common.pyx because it changed.
Compiling ./pyspades/world.pyx because it changed.
Compiling ./pyspades/loaders.pyx because it changed.
Compiling ./pyspades/mapmaker.pyx because it changed.
Cythonizing ./pyspades/bytes.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cpdef int readByte(self, bint unsigned = ?) except INT_ERROR
    cpdef int readShort(self, bint unsigned = ?, bint big_endian = ?) \
                        except INT_ERROR
    cpdef long long readInt(self, bint unsigned = ?, bint big_endian = ?) \
                            except LONG_LONG_ERROR
    cpdef float readFloat(self, bint big_endian = ?) except FLOAT_ERROR
                        ^
------------------------------------------------------------

pyspades/bytes.pxd:19:25: C method 'readFloat' is declared but not defined
Traceback (most recent call last):
  File "build.py", line 26, in <module>
    ext_modules = cythonize(ext_modules)
  File "/home/archie/PySnip-master/venv/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "/home/archie/PySnip-master/venv/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ./pyspades/bytes.pyx
running build_ext
cythoning enet.pyx to enet.c
building 'enet' extension
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet.c -o build/temp.linux-x86_64-2.7/enet.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/list.c -o build/temp.linux-x86_64-2.7/enet/list.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/callbacks.c -o build/temp.linux-x86_64-2.7/enet/callbacks.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/host.c -o build/temp.linux-x86_64-2.7/enet/host.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/peer.c -o build/temp.linux-x86_64-2.7/enet/peer.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/packet.c -o build/temp.linux-x86_64-2.7/enet/packet.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/compress.c -o build/temp.linux-x86_64-2.7/enet/compress.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/protocol.c -o build/temp.linux-x86_64-2.7/enet/protocol.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/win32.c -o build/temp.linux-x86_64-2.7/enet/win32.o -O3
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -DHAS_POLL -DHAS_FCNTL -DHAS_MSGHDR_FLAGS -DHAS_SOCKLEN_T -DHAS_GETHOSTBYNAME_R -DHAS_GETHOSTBYADDR_R -Ienet/include/ -I/usr/include/python2.7 -c enet/unix.c -o build/temp.linux-x86_64-2.7/enet/unix.o -O3
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/enet.o build/temp.linux-x86_64-2.7/enet/list.o build/temp.linux-x86_64-2.7/enet/callbacks.o build/temp.linux-x86_64-2.7/enet/host.o build/temp.linux-x86_64-2.7/enet/peer.o build/temp.linux-x86_64-2.7/enet/packet.o build/temp.linux-x86_64-2.7/enet/compress.o build/temp.linux-x86_64-2.7/enet/protocol.o build/temp.linux-x86_64-2.7/enet/win32.o build/temp.linux-x86_64-2.7/enet/unix.o -L/usr/lib -lpython2.7 -o /home/archie/PySnip-master/enet/enet.so
```

With version 0.21.2, however, everything compiles fine.

**Comment by NateShoffner** [comment]
https://github.com/NateShoffner/PySnip/commit/6f1b9733136fc550b34595c9053aa090d98c74dc should fix this. Seems 0.22 is just more picky about .pxd header signatures with ambiguous excepts.
