### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ediblebird** [NateShoffner/PySnip#19]
Whenever I try to run either of the two latest releases, i get this error message:

Traceback (most recent call last):
  File "run.py", line 123, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "pyspades\server.pyo", line 27, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "pyspades\master.pyo", line 103, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "pyspades\web.pyo", line 2, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "twisted\web\client.pyo", line 42, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "twisted\internet\endpoints.pyo", line 44, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "twisted\internet\stdio.pyo", line 28, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "twisted\internet\_win32stdio.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 98, in load_module
ImportError: MemoryLoadLibrary failed loading win32api.pyd

Im running windows 7 professional 64bit.

**Comment by TheRealOrangus** [comment]
I have windows 7 too, but 32bit, and absolutley the same error,
