### ISSUE TITLE
0.75 win32 release broken

### ISSUE THREAD

**Issue by MuffinTastic** [NateShoffner/PySnip#22]
0.75 win32 release revision f8808c5 has a fatal exception occur every time you attempt to start it:

```2017-09-19 12:34:12-0700 [-] Unhandled error in Deferred:
2017-09-19 12:34:12-0700 [-] Unhandled Error
        Traceback (most recent call last):
          File "twisted\internet\base.pyo", line 1192, in run

          File "twisted\internet\base.pyo", line 1201, in mainLoop

          File "twisted\internet\base.pyo", line 824, in runUntilCurrent

          File "twisted\internet\task.pyo", line 218, in __call__

        --- <exception caught here> ---
          File "twisted\internet\defer.pyo", line 140, in maybeDeferred

          File "pyspades\server.pyo", line 1578, in update

          File "pyspades\server.pyo", line 1597, in update_network

          File "pyspades\contained.pyx", line 104, in pyspades.contained.WorldUpdate.items.__set__ (./pyspades/contained.cpp:5397)

        exceptions.TypeError: Expected dict, got list
```

I'd _imagine_ this has something to do with crossover from the 0.76 branch while packaging the exe, but I'm really not sure. pls fix asap :)

**Comment by 10se1ucgo** [comment]
ill break u kid

**Comment by ghost** [comment]
I have the same error. Can't seem to work around it; the 0.76 release works fine though.

**Comment by Kuunikal** [comment]
I love how it's still broken!

**Comment by noway** [comment]
Phenomenal indeed! (Oups i'm a contributor!)
