### ISSUE TITLE
A little late to the game...

### ISSUE THREAD

**Issue by roadapathy** [NateShoffner/PySnip#24]
I had some errors and it seems like there is a dependency missing- but I followed every guide I could find.

2019-06-04 17:31:27-0500 [-] pyspades server started on Tue Jun  4 17:31:27 2019
2019-06-04 17:31:27-0500 [-] Log opened.
2019-06-04 17:31:27-0500 [-] Traceback (most recent call last):
2019-06-04 17:31:27-0500 [-]   File "run.py", line 1081, in <module>
2019-06-04 17:31:27-0500 [-]     protocol_instance = protocol_class(interface, config)
2019-06-04 17:31:27-0500 [-]   File "./scripts/disco.py", line 39, in __init__
2019-06-04 17:31:27-0500 [-]     protocol.__init__(self, *arg, **kw)
2019-06-04 17:31:27-0500 [-]   File "run.py", line 694, in __init__
2019-06-04 17:31:27-0500 [-]     ServerProtocol.__init__(self, port, interface)
2019-06-04 17:31:27-0500 [-]   File "../pyspades/server.py", line 1481, in __init__
2019-06-04 17:31:27-0500 [-]     BaseProtocol.__init__(self, *arg, **kw)
2019-06-04 17:31:27-0500 [-]   File "../pyspades/protocol.py", line 82, in __init__
2019-06-04 17:31:27-0500 [-]     address = enet.Address(interface, port)
2019-06-04 17:31:27-0500 [-]   File "enet.pyx", line 252, in enet.Address.__init__
2019-06-04 17:31:27-0500 [-]   File "enet.pyx", line 287, in enet.Address.host.__set__
2019-06-04 17:31:27-0500 [-] IOError: Resolution failure!

I am using Xubuntu 18.04 with these dependencies:
sudo apt-get install python2.7 python2.7-dev python-setuptools python-twisted mercurial gcc g++ zope.interface virtualenv python-pip python-dev cython3 libssl-dev python-setuptools libssl-dev

Then I run this:
virtualenv -p python2 venv;source ./venv/bin/activate

pip install cython twisted jinja2 pillow pygeoip pycrypto pyasn1 geocity cryptography cffi service_identity pyopenssl

The server doesn't run. Just gives the above errors. I had it working briefly but something fouled up. I'm wondering if I have the wrong version of something...?

**Comment by roadapathy** [comment]
satisfied: cython in openspades/PySnip/venv/lib/python2.7/site-packages (0.29.10)
satisfied: twisted in openspades/PySnip/venv/lib/python2.7/site-packages (19.2.0)
satisfied: jinja2 in openspades/PySnip/venv/lib/python2.7/site-packages (2.10.1)
satisfied: pillow in openspades/PySnip/venv/lib/python2.7/site-packages (6.0.0)
satisfied: pygeoip in openspades/PySnip/venv/lib/python2.7/site-packages (0.3.2)
satisfied: pycrypto in openspades/PySnip/venv/lib/python2.7/site-packages (2.6.1)
satisfied: pyasn1 in openspades/PySnip/venv/lib/python2.7/site-packages (0.4.5)
satisfied: Automat>=0.3.0 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (0.7.0)
satisfied: zope.interface>=4.4.2 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (4.6.0)
satisfied: PyHamcrest>=1.9.0 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (1.9.0)
satisfied: constantly>=15.1 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (15.1.0)
satisfied: incremental>=16.10.1 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (17.5.0)
satisfied: attrs>=17.4.0 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (19.1.0)
satisfied: hyperlink>=17.1.1 in openspades/PySnip/venv/lib/python2.7/site-packages (from twisted) (19.0.0)
satisfied: MarkupSafe>=0.23 in openspades/PySnip/venv/lib/python2.7/site-packages (from jinja2) (1.1.1)
satisfied: six in openspades/PySnip/venv/lib/python2.7/site-packages (from Automat>=0.3.0->twisted) (1.12.0)
satisfied: setuptools in openspades/PySnip/venv/lib/python2.7/site-packages (from zope.interface>=4.4.2->twisted) (41.0.1)
satisfied: idna>=2.5 in openspades/PySnip/venv/lib/python2.7/site-packages (from hyperlink>=17.1.1->twisted) (2.8)

**Comment by samuelallan72** [comment]
pysnip hasn't been maintained for years so I doubt you'll get any support for this. Check out https://github.com/piqueserver/piqueserver instead! :)

**Comment by roadapathy** [comment]
I was just looking at that. I saw they have updated files. Ok, I will use that! thank you.
