### ISSUE TITLE
Expected dict, got list

### ISSUE THREAD

**Issue by FlorianLebecque** [NateShoffner/PySnip#25]
2020-01-09 17:11:01+0100 [-] Started server...
2020-01-09 17:11:01+0100 [-] Unhandled error in Deferred:
2020-01-09 17:11:01+0100 [-] Unhandled Error
        Traceback (most recent call last):
          File "twisted\internet\base.pyo", line 1192, in run

          File "twisted\internet\base.pyo", line 1201, in mainLoop

          File "twisted\internet\base.pyo", line 824, in runUntilCurrent

          File "twisted\internet\task.pyo", line 218, in __call__

        --- <exception caught here> ---
          File "twisted\internet\defer.pyo", line 140, in maybeDeferred

          File "pyspades\server.pyo", line 1578, in update

          File "pyspades\server.pyo", line 1597, in update_network

          File "pyspades\contained.pyx", line 104, in pyspades.contained.WorldUpdate.items.__set__ (./pyspades/contained.cpp:5397)

        exceptions.TypeError: Expected dict, got list

2020-01-09 17:11:01+0100 [HTTPPageGetter,client] Server identifier is aos://1610477649:32887

**Comment by NotAFile** [comment]
Not sure what causes this, but pysnip is unmaintained. Check out https://github.com/piqueserver/piqueserver for an actively maintained fork with many new features and bugfixes.
